[build]
  publish = "."

[build.environment]
  NODE_VERSION = "18"

# Pluginleri devre dışı bırak
[[plugins]]
  package = "netlify-plugin-ghost"
  enabled = false

[[plugins]]  
  package = "@netlify/plugin-simple-analytics"
  enabled = false

[[plugins]]
  package = "@netlify/plugin-neon"
  enabled = false

[[plugins]]
  package = "@netlify/plugin-async-workloads"
  enabled = false