services:
  - type: web
    name: tozyapi-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python src/main.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_API_BASE
        value: https://api.openai.com/v1
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: /opt/render/project/src
    healthCheckPath: /api/users
    autoDeploy: true

